config/routes.rb
Chaseuni::Application.routes.draw do
  
  resources :questions

  get 'enrollments', to: 'courses#enrollments'
  
  resources :courses do
    member do
      post 'enroll'

    end
    resources :exams

  end

  resources :faculties

  resources :pages
   
  root :to => 'courses#index'
  
  devise_for :users, :controllers => {
    :registrations => 'registrations',
    :passwords     => 'passwords',
    :sessions      => 'sessions',
    :confirmations => 'confirmations'
  }
  devise_scope :user do
    get '/login'  => 'sessions#new'
    get '/logout' => 'sessions#destroy'
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  validates :user_id, :course_id, :title, :presence => true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :get_courses, only: [:edit, :new, :update, :create]
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  def get_courses
    @courses = Course.get_key_values
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :description, :user_id, :course_id, :is_multiple_choice)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
<% if @question.errors.any? %>
<div class="alert alert-danger">
	<h4><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h4>

	<ul>
		<% @question.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="form-item">
	<%= f.label :title %>
	<%= f.text_field :title, :class => "form-control" %>
</div>
<div class="form-item">
	<%= f.label :description %>
	<%= f.text_area :description, :class => "form-control", :rows => 4 %>
</div>

<div class="form-item">
	<%= f.label :course_id %>
	<%= f.select :course_id, options_for_select(@courses, @question.course_id),{},{ :class => "form-control"} %>
</div>
<%if !@question.is_multiple_choice%>
<div class="form-item">
	<%= f.check_box :is_multiple_choice %> Is multiple choice question?
</div>
<%end%>
<div class="actions">
	<%= f.submit(:class => "btn btn-primary") %>
</div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class="table-responsive">
<h3>Listing questions</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Course</th>
      <th>Is multiple choice</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.description %></td>
        <td><%= question.course.title %></td>
        <td><%= question.is_multiple_choice == true ? "Yes" : "No" %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @question.description %>
</p>

<p>
  <strong>Course:</strong>
  <%= @question.course.title %>
</p>

<p>
  <strong>Is multiple choice:</strong>
  <%= @question.is_multiple_choice %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>