config/routes.rb
Chaseuni::Application.routes.draw do
  
  resources :questions

  get 'enrollments', to: 'courses#enrollments'
  
  resources :courses do
    member do
      post 'enroll'

    end
    resources :exams

  end

  resources :faculties

  resources :pages
   
  root :to => 'courses#index'
  
  devise_for :users, :controllers => {
    :registrations => 'registrations',
    :passwords     => 'passwords',
    :sessions      => 'sessions',
    :confirmations => 'confirmations'
  }
  devise_scope :user do
    get '/login'  => 'sessions#new'
    get '/logout' => 'sessions#destroy'
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chaseuni</title>
  <%= stylesheet_link_tag    "application", "custom", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header id="header" class="navbar navbar-fixed-top bg-white box-shadow" data-offset-top="1" data-spy="affix">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">
				<%= image_tag("logo.png", :alt => "Chaseuni") %>
			</a>
		 	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		      <span class="sr-only">Toggle navigation</span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		    </button>
		 </div>
		  <!-- Collect the nav links, forms, and other content for toggling -->
		  <div class="collapse navbar-collapse">
		    <ul class="nav navbar-nav navbar-right">
				 <li><%=link_to "My enrollments", enrollments_path%></li>
				 <li class="dropdown">
			        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Faculties <b class="caret"></b></a>
			        <ul class="dropdown-menu">
			          <li><%=link_to "List all faculties", faculties_path%></li>
			          <li><%=link_to "Create a new faculty", new_faculty_path%></li>
			        </ul>
				</li>
				<li class="dropdown">
			        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Questions <b class="caret"></b></a>
			        <ul class="dropdown-menu">
			          <li><%=link_to "List all questions", questions_path%></li>
			          <li><%=link_to "Create a new question", new_question_path%></li>
			        </ul>
				</li>
			     <li class="dropdown">
		        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Courses <b class="caret"></b></a>
		        <ul class="dropdown-menu">
		          <li><%=link_to "List all courses", courses_path%></li>
		          <li><%=link_to "Create a new course", new_course_path%></li>
		          <li><a href="#">Dummy link3</a></li>
		          <li class="divider"></li>
		          <li><a href="#">Dummy link4</a></li>
		        </ul>
		      </li>
		      <li>
		      	<%= @user_email  %>
		      </li>
		      <li>
		      	<%if user_signed_in?%>
					<%=link_to "logout",destroy_user_session_path, :method => 'delete' %>
				<%end%>
		      </li>
		    </ul>
		  </div><!-- /.navbar-collapse -->
	</div>
</header>
<section id="content">
	<% if notice %>
	<div class="alert alert-info"><%= notice %></div>
	<% end %>
	<% if alert %>
	<div class="alert alert-danger"><%= alert %></div>
	<% end %>
	<div class="bg-gray">
		<div class="container container-sh" >
		<%if user_signed_in?%>
			<%= yield %>
		<%else%>
		<div class="pull-right col-md-3">
		<div class="panel panel-primary">
			<div class="panel-heading">
		    <h3 class="panel-title"><i class="fa fa-user"></i> <%=yield(:heading)%></h3>
		  </div>
		  <div class="panel-body">
		   <%=yield%>
		  </div>
		  <div class="panel-footer">
		  	<%= render "devise/shared/links" %>
		  </div>
		</div>
		</div>
		<%end%>
		</div>
		</div>	
</div>
</body>
</html>

app/views/layouts/modal.html.erb
<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><%=yield(:heading)%> </h4>
      </div>
      <div class="modal-body">
       <%=yield%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->